// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1070
package tour

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/emo-lang/website-cn/app/views/emocode"
	"github.com/emo-lang/website-cn/app/views/layouts"
)

const tour1 = `// ---- 1 · 绑定与字符串 ----
const who = "世界"
var visits = 6
visits = visits * 7
println("hello, ${who} — six sevens are ${visits}")

// 插值可以装任何表达式, 中文就是普通的字符串数据
const item = "伞"
println("one ${item} costs ${19 + 9} yuan")`

const tour2 = `// ---- 2 · 类: 不可变值类型 ----
class User {
  def init(name String, age Int64) {
    self.name = name
    self.age = age
  }

  def describe() String {
    return "${self.name},age ${self.age}"
  }

  def adult?() Bool {
    return self.age >= 18
  }
}

const ming = User.new(name: "王晓明", age: 28)
println(ming.describe())
println("adult? ${ming.adult?()}")
// 字段在 init 之后冻结, 相等比较的是内容:
println(ming == User.new(name: "王晓明", age: 28))`

const tour3 = `// ---- 3 · 接口: 形状即契约 ----
// 哪里都没有 implements: 形状匹配, 即满足接口。
interface Greeter {
  def greet() String
}

class Machine {
  def greet() String {
    return "[beep] 你好"
  }
}

class Friend {
  def greet() String {
    return "很高兴见到你"
  }
}

def welcome(g Greeter) String {
  if g.is(Machine) {
    return "a machine says: ${g.greet()}"
  }
  return "a friend says: ${g.greet()}"
}

println(welcome(Machine.new()))
println(welcome(Friend.new()))`

const tour4 = `// ---- 4 · 枚举与标签惯用法 ----
// 枚举是封闭的有名值集合, 成员不携带数据。
// 需要携带数据时, 标签放进元组, case 按位置解构。
enum Outcome { ok, err }

def classify(age Int64) (Outcome, String) {
  if age >= 18 {
    return (Outcome.ok, "adult")
  }
  return (Outcome.err, "minor")
}

case classify(28) {
  (Outcome.ok, label) -> { println("28 -> ${label}") }
  (Outcome.err, label) -> { println("28 -> ${label}") }
}

// 分支可以带守卫:
case (Outcome.ok, 42) {
  (Outcome.ok, v) when v > 40 -> { println("a big answer: ${v}") }
  (Outcome.ok, v) -> { println("a small answer: ${v}") }
  (Outcome.err, label) -> { println("no answer: ${label}") }
}`

const tour5 = `// ---- 5 · 数组: 定长、变换、永不就地修改 ----
const nums = [3, 1, 2]
println(nums[0] + nums.length())
// 变换返回新数组, 原数组纹丝不动:
const more = nums.append(9)
println(more.length())
println(nums.length())
println([1, 2] == [1, 2])`

const tour6 = `// ---- 6 · 可变性, 一层一层来 ----
// var 显式且块作用域; Box 是一个进程拥有的唯一长期可变单元
// —— 只有 read 与 replace, 刻意没有别的。
var tally = 0
tally = tally + 1
tally = tally + 10
println(tally)

const total = Box.new(0)
total.replace(total.read() + 5)
total.replace(total.read() + 6)
println(total.read())`

const tour7 = `// ---- 7 · 代码块: 唯一的函数记法 ----
// 箭头块是匿名函数; 调用可以尾随一个代码块,
// 回调与迭代因此保持同一种记法。
const twice = -> (n Int64) { return n * 2 }
println(twice(21))

def walk(xs Array[Int64], i Int64, f Block) Int64 {
  if i == xs.length() {
    return 0
  }
  f(xs[i])
  return walk(xs, i + 1, f)
}

walk([10, 20, 30], 0) -> (v Int64) {
  println(v)
  return v
}`

const tour8 = `// ---- 8 · 进程: 三个进程, 一条消息链 ----
def feed(wh Pid, i Int64) Int64 {
  if i > 3 {
    wh <- "done"
    return 0
  }
  wh <- (i, i)
  return feed(wh, i + 1)
}

const rep = do reporter.run(0, self_pid())
const wh = do warehouse.run(rep)
feed(wh, 1)

receive {
  (who, handled) -> { println("handled ${handled} orders") }
}`

func Index() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<style>\n\t\t\t.tour-step { margin-bottom: 3.5rem; scroll-margin-top: 5rem; }\n\t\t\t.tour-step h2 { margin: 0 0 0.6rem; font-size: 1.35rem; letter-spacing: -0.01em; }\n\t\t\t.tour-step h2 .num {\n\t\t\t\tdisplay: inline-flex; align-items: center; justify-content: center;\n\t\t\t\twidth: 1.9rem; height: 1.9rem; margin-right: 0.6rem;\n\t\t\t\tborder-radius: 50%; background: var(--brand); color: var(--brand-ink);\n\t\t\t\tfont-size: 0.95rem; font-weight: 700; vertical-align: 0.15em;\n\t\t\t}\n\t\t\t.tour-step > p { margin: 0 0 1rem; color: var(--muted); }\n\t\t</style> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = layouts.Nav("tour").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<main><section class=\"page-hero\"><div class=\"container\"><h1>语言漫游</h1><p>一个程序，从上到下读完，每个小节几行代码就把事情说清楚。 Emo 的设计规则是：一切所见即所得 —— 调用有括号，返回写出来，可变性永远拼出来。 把各节拼成一个 <code>main.emo</code>，<code>emo run main.emo</code> 即可运行。</p></div></section><section class=\"section\" style=\"border-top: none; padding-top: 1rem;\"><div class=\"container\"><div class=\"tour-step\" id=\"bindings\"><h2><span class=\"num\">1</span>绑定与字符串</h2><p><code>const</code> 不变，<code>var</code> 可变但出不了块。字符串永远双引号，插值只有一种形状，花括号里可以装任意表达式。</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = emocode.Terminal("main.emo", tour1).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><div class=\"tour-step\" id=\"classes\"><h2><span class=\"num\">2</span>类：不可变值类型</h2><p>字段只在 <code>init</code> 里诞生，之后冻结；两个内容相同的实例 <code>==</code>。谓词方法以 <code>?</code> 结尾。</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = emocode.Terminal("main.emo", tour2).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div><div class=\"tour-step\" id=\"interfaces\"><h2><span class=\"num\">3</span>接口：形状即契约</h2><p>接口属于调用方。类不必声明实现任何接口 —— 形状对上，契约就成立。</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = emocode.Terminal("main.emo", tour3).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div><div class=\"tour-step\" id=\"enums\"><h2><span class=\"num\">4</span>枚举与标签惯用法</h2><p>枚举成员不携带数据。需要数据时，标签骑在元组里，<code>case</code> 按位置解构，还能带守卫。</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = emocode.Terminal("main.emo", tour4).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</div><div class=\"tour-step\" id=\"arrays\"><h2><span class=\"num\">5</span>数组：定长、变换、永不就地修改</h2><p>变换总是返回新数组；<code>==</code> 逐元素比较内容。</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = emocode.Terminal("main.emo", tour5).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div><div class=\"tour-step\" id=\"mutability\"><h2><span class=\"num\">6</span>可变性，一层一层来</h2><p><code>var</code> 活不过它的块；长期状态只有 <code>Box</code>，只有 <code>read</code> 与 <code>replace</code>。</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = emocode.Terminal("main.emo", tour6).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</div><div class=\"tour-step\" id=\"blocks\"><h2><span class=\"num\">7</span>代码块：唯一的函数记法</h2><p><code>-&gt; (x) &#123; ... &#125;</code> 是匿名函数；<code>def</code> 是它的命名形态。尾随代码块让回调与迭代保持同一种记法。</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = emocode.Terminal("main.emo", tour7).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</div><div class=\"tour-step\" id=\"processes\"><h2><span class=\"num\">8</span>进程：一条消息链</h2><p><code>do</code> 起进程，<code>&lt;-</code> 发消息，<code>receive</code> 选择性接收。尾调用有保证，递归就是收信循环。</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = emocode.Terminal("main.emo", tour8).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</div></div></section></main>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = layouts.Footer().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.Base("语言漫游 — Emo", "一个程序读懂 Emo：绑定、类、接口、枚举、数组、可变性、代码块与进程，每个小节几行代码。").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
