// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1070
package emocode

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// Styles renders the shared CSS for Emo code terminals. Include it once per
// page (the layout does this).
func Styles() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<style>\n\t\t.emo-terminal {\n\t\t\tborder: 1px solid var(--border);\n\t\t\tborder-radius: 0.9rem;\n\t\t\toverflow: hidden;\n\t\t\tbackground: #1a1a1c;\n\t\t\tbox-shadow: var(--shadow);\n\t\t}\n\t\t.emo-terminal-bar {\n\t\t\tdisplay: flex;\n\t\t\talign-items: center;\n\t\t\tgap: 0.5rem;\n\t\t\tpadding: 0.6rem 0.9rem;\n\t\t\tborder-bottom: 1px solid #2c2c30;\n\t\t\tbackground: #222225;\n\t\t}\n\t\t.emo-dot { width: 0.72rem; height: 0.72rem; border-radius: 50%; }\n\t\t.emo-dot.red { background: #ff5f57; }\n\t\t.emo-dot.yellow { background: #febc2e; }\n\t\t.emo-dot.green { background: #28c840; }\n\t\t.emo-terminal-title {\n\t\t\tmargin-left: 0.4rem;\n\t\t\tcolor: #8e8e96;\n\t\t\tfont-size: 0.78rem;\n\t\t\tfont-family: ui-monospace, \"SF Mono\", SFMono-Regular, Menlo, Consolas, \"Liberation Mono\", monospace;\n\t\t}\n\t\t.emo-code {\n\t\t\tmargin: 0;\n\t\t\tpadding: 1.2rem 1.4rem;\n\t\t\tfont-family: ui-monospace, \"SF Mono\", SFMono-Regular, Menlo, Consolas, \"Liberation Mono\", monospace;\n\t\t\tfont-size: 0.8rem;\n\t\t\tline-height: 1.6;\n\t\t\tcolor: #e8e8ec;\n\t\t\toverflow-x: auto;\n\t\t\ttab-size: 2;\n\t\t\twhite-space: pre;\n\t\t}\n\t\t.emo-code code { font-family: inherit; font-size: inherit; background: none; border-radius: 0; padding: 0; }\n\t\t.emo-code .tok-k { color: #9ea0f5; }              /* keywords */\n\t\t.emo-code .tok-t { color: #efbf6b; }              /* types */\n\t\t.emo-code .tok-s { color: #a9dc76; }              /* strings */\n\t\t.emo-code .tok-n { color: #d2a8ff; }              /* numbers */\n\t\t.emo-code .tok-f { color: #79c0ff; }              /* call sites */\n\t\t.emo-code .tok-c { color: #7a7a84; font-style: italic; } /* comments */\n\t\t.emo-code .tok-o { color: #ff7b93; }              /* <- and -> */\n\t</style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// Terminal renders src as a highlighted Emo snippet inside a terminal frame.
func Terminal(title string, src string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"emo-terminal\"><div class=\"emo-terminal-bar\"><span class=\"emo-dot red\"></span> <span class=\"emo-dot yellow\"></span> <span class=\"emo-dot green\"></span> <span class=\"emo-terminal-title\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `emocode/terminal.templ`, Line: 61, Col: 43}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</span></div><pre class=\"emo-code\"><code>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.Raw(Highlight(src)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</code></pre></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
